### ISSUE TITLE
Error 500 occurs when running the application

### ISSUE THREAD

**Issue by Saamiyah** [Front-End-Coders-Mauritius/frontendmu-nuxt#3]
**More info :**
 [nuxt] [request error] Cannot read properties of null (reading 'slice')
  at _sfc_ssrRender
  at renderComponentSubTree
  at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by MrSunshyne** [comment]
Thank you for the bug report. 

We are using Directus Cloud, community edition as the CMS for this site. 

Events are added on directus cloud, they are then fetched via its public api, then rendered on this nuxt project.

![image](https://user-images.githubusercontent.com/1721611/170480095-04e1589e-f329-447d-a99d-343a900494b9.png)


Directus Community Edition shuts itself down when it is inactive. i.e nobody loggedin or edited any event. 
When the api is down, it causes this 500 error. 

The server is found here : https://l4yporup.directus.app/admin
Only the organizers have access to add and edit events

I resumed the cloud server, it should be working again for you again.

**Comment by mgjules** [comment]
The only options I can think of here:
1. Upgrade the subscription
2. Add Cloudflare in-front of the directus API 🤷🏾

**Comment by MrSunshyne** [comment]
Option 2 seems interesting @mgjules, never even thought about that. Is it possible to proxy someone else's api endpoint? :thinking:

**Comment by MrSunshyne** [comment]
This will always happen as long as we use the Directus community edition and someone from the org team doesn't login for 3 days.

Another solution would be to cache the api calls on disk and consume that. closing this issue for now.
